PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>
PREFIX owl:     <http://www.w3.org/2002/07/owl#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX wfprov:  <http://purl.org/wf4ever/wfprov#>
PREFIX ore: 	<http://www.openarchives.org/ore/terms/>
PREFIX wro: 	<http://purl.org/wf4ever/ro#>
PREFIX roevo: 	<http://purl.org/wf4ever/roevo#>
PREFIX wfdesc:  <http://purl.org/wf4ever/wfdesc#>
PREFIX prov:    <http://www.w3.org/ns/prov#>
PREFIX wf4ever: <http://purl.org/wf4ever/wf4ever#>
PREFIX oa:      <http://www.w3.org/ns/oa#>
PREFIX :        <http://w3id.org/s2rwro/md-setup#>

#Question 1
select distinct ?workflow ?source ?process ?dprocess ?input ?dinput ?output ?doutput ?datalink ?ddatalink
where { 
?workflow prov:hadPrimarySource ?source .
?workflow wfdesc:hasInput ?input .
?workflow wfdesc:hasOutput ?output .
?workflow wfdesc:hasSubProcess ?process .
?workflow wfdesc:hasDataLink ?datalink .
?input prov:wasDerivedFrom ?dinput .
?output prov:wasDerivedFrom ?doutput .
?process prov:wasDerivedFrom ?dprocess .
?datalink prov:wasDerivedFrom ?ddatalink .
}

#Question 2
select distinct ?wro ?title ?snapshot ?changes ?change ?concept ?resource ?workflow
where {
?wro a wro:ResearchObject .
?wro dcterms:title ?title .
?snapshot roevo:isSnapshotOf ?wro .
?snapshot roevo:wasChangedBy ?changes .
?changes roevo:hasChange ?change .
?change a ?concept .
?change roevo:relatedResource ?resource .
?workflow wfdesc:hasWorkflowDefinition ?resource .
}